### ISSUE TITLE
Please, using task and async methods for all database examples in next book edition

### ISSUE THREAD

**Issue by P9avel** [markjprice/cs13net9#1]
Hi. For example here.
![image](https://github.com/user-attachments/assets/321f1400-d611-4469-91c6-1e099b32a8e2)

Many people use your book as a textbook and copy examples into working code :) As a result, such code leads to thread pool exhaustion. Please, using task and async methods for all database examples in next book edition

**Comment by markjprice** [comment]
1. When a beginner learns a new topic, it is best to keep it as simple as possible. This is why I use console apps for all examples until I start showing ASP.NET Core projects. Adding `Task` and `async` will clutter the code and confuse some of the readers. 
2. All the code examples use Northwind. No readers use Northwind in their real-world projects, so they shouldn't be copying and pasting the exact code. They should just be using the examples as a textbook and learning about the various ways to query and manipulate data. I think you're worrying about something that doesn't actually happen. 
3. I do agree it's worth adding a section about how to use the `...Async` methods in the EF Core and LINQ chapters and a warning that it is especially important to use them in server-side projects like ASP.NET Core to avoid thread exhaustion, so I will do that in the next edition: https://github.com/markjprice/cs13net9/blob/main/docs/errata/improvements.md#chapter-10---working-with-data-using-entity-framework-core
